#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...dd

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc_frendon" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc_frendon"
fi



alias rm='nocorrect rm'

alias upzprezto='git pull && git submodule update --init --recursive'


# History Search
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey  '^[[A'  history-beginning-search-backward-end
bindkey  '^[[B'  history-beginning-search-forward-end

bindkey  '^[[5~' history-beginning-search-backward-end
bindkey  '^[[6~' history-beginning-search-forward-end


